import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://biz-dev1-auth.kredx.com/realms/Shared/protocol/openid-connect/auth?response_type=code&client_id=shared-client&state=https://biz-dev1.kredx.com/payables/&redirect_uri=https://biz-dev1.kredx.com/login_callback');
    await page.getByLabel('Email').fill('nikhil+abcde3002f@kredx.com');
    await page.getByLabel('Password').click();
    await page.getByLabel('Password').press('CapsLock');
    await page.getByLabel('Password').fill('A');
    await page.getByLabel('Password').press('CapsLock');
    await page.getByLabel('Password').fill('');
    await page.getByLabel('Password').press('CapsLock');
    await page.getByLabel('Password').fill('A');
    await page.getByLabel('Password').press('CapsLock');
    await page.getByLabel('Password').fill('Asdf!234');
    await page.getByLabel('Password').press('Enter');
    await page.getByRole('link', { name: 'Activities' }).click();
    await page.getByRole('link', { name: 'Activities' }).click();
    await page.getByRole('tab', { name: 'Tasks' }).click();
    await page.getByRole('button', { name: 'Create Task' }).click();
    await page.getByLabel('Record Type').click();
    await page.getByTitle('Invoice').getByText('Invoice').click();
    await page.getByRole('combobox', { name: '* Vendor Name :' }).click();
    await page.getByRole('combobox', { name: '* Vendor Name :' }).press('CapsLock');
    await page.getByRole('combobox', { name: '* Vendor Name :' }).fill('SRL SOLUTIONS');
    await page.getByRole('combobox', { name: '* Vendor Name :' }).click();
    await page.getByRole('combobox', { name: '* Vendor Name :' }).fill('SRL SOLUTION');
    await page.locator('div:nth-child(2) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector').click();
    await page.getByRole('combobox', { name: '* Vendor Name :' }).click();
    await page.getByRole('combobox', { name: '* Vendor Name :' }).fill('');
    await page.getByRole('combobox', { name: '* Vendor Name :' }).click();
    await page.getByRole('combobox', { name: '* Vendor Name :' }).press('CapsLock');
    await page.getByRole('combobox', { name: '* Vendor Name :' }).fill('S');
    await page.getByRole('combobox', { name: '* Vendor Name :' }).press('CapsLock');
    await page.getByRole('combobox', { name: '* Vendor Name :' }).fill('Srl solutions');
    await page.getByTitle('SRL Solutions').getByText('SRL Solutions').click();
    await page.locator('.ant-select-selection-overflow').click();
    await page.getByTitle('IN3207010').getByText('IN3207010').click();
    await page.getByPlaceholder('Select date').click();
    await page.getByText('Now').click();
    await page.getByLabel('Purpose').click();
    await page.getByTitle('Dispute Resolution').getByText('Dispute Resolution').click();
    await page.getByLabel('Subject', { exact: true }).click();
    await page.getByLabel('Subject', { exact: true }).fill('D');
    await page.getByLabel('Subject', { exact: true }).press('CapsLock');
    await page.getByLabel('Subject', { exact: true }).fill('Dispute ');
    await page.getByLabel('Subject', { exact: true }).press('CapsLock');
    await page.getByLabel('Subject', { exact: true }).fill('Dispute R');
    await page.getByLabel('Subject', { exact: true }).press('CapsLock');
    await page.getByLabel('Subject', { exact: true }).fill('Dispute Resolution');
    await page.getByLabel('Details').click();
    await page.getByLabel('Details').press('CapsLock');
    await page.getByLabel('Details').fill('D');
    await page.getByLabel('Details').press('CapsLock');
    await page.getByLabel('Details').fill('Dispute ');
    await page.getByLabel('Details').press('CapsLock');
    await page.getByLabel('Details').fill('Dispute R');
    await page.getByLabel('Details').press('CapsLock');
    await page.getByLabel('Details').fill('Dispute Resolution');
    await page.getByRole('button', { name: 'Submit' }).click();
});