import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://biz-dev1-auth.kredx.com/realms/Shared/protocol/openid-connect/auth?response_type=code&client_id=shared-client&state=https://biz-dev1.kredx.com/payables/&redirect_uri=https://biz-dev1.kredx.com/login_callback');
    await page.getByLabel('Email').fill('nikhil+abcde3002f@kredx.com');
    await page.getByLabel('Password').click();
    await page.getByLabel('Password').press('CapsLock');
    await page.getByLabel('Password').fill('A');
    await page.getByLabel('Password').press('CapsLock');
    await page.getByLabel('Password').fill('Asdf!234');
    await page.getByLabel('Password').press('Enter');
    await page.getByRole('link', { name: 'Disputes' }).click();
    await page.getByRole('button', { name: 'Create Dispute' }).click();
    await page.getByLabel('Record Type').click();
    await page.getByText('Vendor', { exact: true }).click();
    await page.getByLabel('Vendor Name').click();
    await page.getByLabel('Vendor Name').fill('srl solutions');
    await page.getByTitle('SRL Solutions').getByText('SRL Solutions').click();
    await page.getByLabel('Subject', { exact: true }).click();
    await page.getByLabel('Subject', { exact: true }).press('CapsLock');
    await page.getByLabel('Subject', { exact: true }).fill('D');
    await page.getByLabel('Subject', { exact: true }).press('CapsLock');
    await page.getByLabel('Subject', { exact: true }).fill('Dispute#2');
    await page.getByLabel('Reason Category').click();
    await page.getByTitle('Invoice Issue').getByText('Invoice Issue').click();
    await page.getByLabel('Reason Sub Category').click();
    await page.getByTitle('Missing Items').getByText('Missing Items').click();
    await page.getByLabel('Priority').click();
    await page.getByTitle('Medium').getByText('Medium').click();
    await page.getByText('Private', { exact: true }).click();
    await page.getByText('Public', { exact: true }).click();
    await page.getByLabel('Details').click();
    await page.getByLabel('Details').press('CapsLock');
    await page.getByLabel('Details').fill('D');
    await page.getByLabel('Details').press('CapsLock');
    await page.getByLabel('Details').fill('Dispute');
    await page.getByLabel('Assigned To').click();
    await page.getByLabel('Assigned To').press('CapsLock');
    await page.getByLabel('Assigned To').press('CapsLock');
    await page.getByTitle('Admin').getByText('Admin').click();
    await page.getByRole('button', { name: 'Submit' }).click();
});