import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://biz-dev1-auth.kredx.com/realms/Shared/protocol/openid-connect/auth?response_type=code&client_id=shared-client&state=https://biz-dev1.kredx.com/receivables/&redirect_uri=https://biz-dev1.kredx.com/login_callback');
  await page.getByLabel('Email').fill('nikhil+abcde3002f@kredx.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('A');
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('');
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('A');
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('Asdf!234');
  await page.getByLabel('Password').press('Enter');
  await page.getByRole('link', { name: 'Settings' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Users' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('button', { name: 'Create New User' }).click();
  await page1.getByPlaceholder('First name').click();
  await page1.getByPlaceholder('First name').press('CapsLock');
  await page1.getByPlaceholder('First name').fill('B');
  await page1.getByPlaceholder('First name').press('CapsLock');
  await page1.getByPlaceholder('First name').fill('Brenda');
  await page1.getByPlaceholder('Last name').click();
  await page1.getByPlaceholder('Last name').press('CapsLock');
  await page1.getByPlaceholder('Last name').fill('G');
  await page1.getByPlaceholder('Last name').press('CapsLock');
  await page1.getByPlaceholder('Last name').fill('Gomes');
  await page1.getByPlaceholder('Email').click();
  await page1.getByPlaceholder('Email').fill('brenda+testuser806@kredx.com');
  await page1.getByPlaceholder('Mobile').click();
  await page1.getByPlaceholder('Mobile').fill('9999999999');
  await page1.getByPlaceholder('Employee ID').click();
  await page1.getByPlaceholder('Employee ID').fill('9801');
  await page1.getByPlaceholder('Designation').click();
  await page1.getByPlaceholder('Designation').press('CapsLock');
  await page1.getByPlaceholder('Designation').fill('M');
  await page1.getByPlaceholder('Designation').press('CapsLock');
  await page1.getByPlaceholder('Designation').fill('Manager');
  await page1.locator('#rc_select_1').click();
  await page1.locator('#rc_select_1').click();
  await page1.locator('#rc_select_1').fill('admin');
  await page1.getByRole('dialog').getByText('ADMIN', { exact: true }).click();
  await page1.locator('#rc_select_2').click();
  await page1.getByTitle('Organization').getByText('Organization').click();
  await page1.locator('#rc_select_3').click();
  await page1.locator('#rc_select_3').fill('admin');
  await page1.getByTitle('Admin').getByText('Admin').click();
  await page1.locator('#rc_select_4').click();
  await page1.locator('#rc_select_4').fill('orga');
  await page1.getByRole('dialog').getByText('Organization').nth(2).click();
  await page1.getByRole('button', { name: 'Create', exact: true }).click();
  await page1.getByLabel('Active', { exact: true }).check();
  await page.pause();
  await page1.getByRole('button', { name: 'Create', exact: true }).click();
});